spring.datasource.url=jdbc:postgresql://localhost:5432/fridge_raider_development
spring.datasource.username=
spring.datasource.password=
spring.jpa.show-sql=true
debug=true
logging.level.root=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG