spring.datasource.url=jdbc:postgresql://localhost:5432/fridge_raider_development
spring.datasource.username=
spring.datasource.password=
flyway.baseline-on-migrate=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect