TRUNCATE TABLE ingredients RESTART IDENTITY CASCADE;

INSERT INTO ingredients (name) VALUES
                                   ('advocaat'),
                                   ('agave nectar'),
                                   ('agave syrup'),
                                   ('alcohol-free spirit'),
                                   ('alfalfa'),
                                   ('allspice'),
                                   ('almond'),
                                   ('almond butter'),
                                   ('almond extract'),
                                   ('almond flour'),
                                   ('almond milk'),
                                   ('amaretto'),
                                   ('anchovy'),
                                   ('anchovy fillet'),
                                   ('angostura bitters'),
                                   ('another salad'),
                                   ('aperol'),
                                   ('apple'),
                                   ('apple cider vinegar'),
                                   ('apple juice'),
                                   ('apple sauce'),
                                   ('apricot'),
                                   ('apricot conserve'),
                                   ('apricot glaze'),
                                   ('aquafaba'),
                                   ('artichoke'),
                                   ('asparagus'),
                                   ('assam tea'),
                                   ('atta'),
                                   ('aubergine'),
                                   ('avocado'),
                                   ('avocado oil'),
                                   ('açaí powder'),
                                   ('baby'),
                                   ('bacon'),
                                   ('bagel'),
                                   ('baguette'),
                                   ('baharat spice mix'),
                                   ('baked bean'),
                                   ('baking powder'),
                                   ('balsamic vinegar'),
                                   ('bamboo shoot'),
                                   ('banana'),
                                   ('bananas cut into'),
                                   ('bap'),
                                   ('barbie-style doll'),
                                   ('barley'),
                                   ('basil'),
                                   ('bay leaf'),
                                   ('bbq sauce'),
                                   ('bean salad'),
                                   ('beansprouts'),
                                   ('beef'),
                                   ('beer'),
                                   ('beetroot'),
                                   ('berries of your choice'),
                                   ('berry'),
                                   ('berry mix'),
                                   ('bicarbonate of soda'),
                                   ('biscuit'),
                                   ('black'),
                                   ('black bean'),
                                   ('black fondant icing'),
                                   ('black kalamata olive'),
                                   ('black olive'),
                                   ('black pepper'),
                                   ('black ready-to-roll icing'),
                                   ('black sugarpaste'),
                                   ('black teabag'),
                                   ('black truffle'),
                                   ('black urid bean'),
                                   ('black-eyed bean'),
                                   ('blackberry'),
                                   ('blood orange'),
                                   ('blue'),
                                   ('blue cheese'),
                                   ('blue curaçao'),
                                   ('blue sugarpaste'),
                                   ('blueberry'),
                                   ('boiling water'),
                                   ('bone-in'),
                                   ('boneles'),
                                   ('borlotti bean'),
                                   ('botija peruvian'),
                                   ('bought good-quality dressing'),
                                   ('bouillon'),
                                   ('bouillon powder'),
                                   ('bouquet garni'),
                                   ('box tunworth'),
                                   ('braising'),
                                   ('brandy'),
                                   ('brazil nut'),
                                   ('bread'),
                                   ('breadcrumbs'),
                                   ('breadstick'),
                                   ('brewed black coffee'),
                                   ('brewed very strong coffee'),
                                   ('brie'),
                                   ('brioche bun'),
                                   ('brioche hot dog bun'),
                                   ('broad bean'),
                                   ('broccoli'),
                                   ('brown anchovy'),
                                   ('brown breadcrumbs'),
                                   ('brown ready-to-roll icing'),
                                   ('brown sugarpaste'),
                                   ('brussels sprouts'),
                                   ('bucatini'),
                                   ('buckwheat'),
                                   ('bulgur wheat'),
                                   ('bun'),
                                   ('burger bun'),
                                   ('burger buns and salad'),
                                   ('burger sauce of your choice'),
                                   ('butchers string'),
                                   ('butter'),
                                   ('butter bean'),
                                   ('buttermilk'),
                                   ('buttery mash'),
                                   ('button'),
                                   ('cabbage'),
                                   ('cacao nib'),
                                   ('cacao powder'),
                                   ('cajun seasoning'),
                                   ('cajun seasoning mix'),
                                   ('cajun spice mix'),
                                   ('cajun-style seasoning'),
                                   ('cake smoother'),
                                   ('cal oil spray'),
                                   ('calvado'),
                                   ('candle'),
                                   ('canned'),
                                   ('cannellini bean'),
                                   ('caper'),
                                   ('caramel'),
                                   ('caramel flavouring'),
                                   ('caramel sauce'),
                                   ('caraway seed'),
                                   ('cardamom'),
                                   ('carrot'),
                                   ('carton 50% fat crème fraîche'),
                                   ('carton buttermilk'),
                                   ('carton crème fraîche'),
                                   ('carton of cres'),
                                   ('cashew'),
                                   ('cassi'),
                                   ('caster'),
                                   ('cauliflower'),
                                   ('cavolo nero'),
                                   ('cayenne pepper'),
                                   ('celeriac'),
                                   ('celeriac peeled and diced'),
                                   ('celery'),
                                   ('chamomile tea bag'),
                                   ('chantenay'),
                                   ('chard'),
                                   ('chargrilled vegetable'),
                                   ('charred brussels sprouts'),
                                   ('cheddar'),
                                   ('cheese'),
                                   ('cherries with'),
                                   ('cherry'),
                                   ('cherry tomato'),
                                   ('chervil'),
                                   ('chestnut'),
                                   ('chewing gum'),
                                   ('chia seed'),
                                   ('chicken'),
                                   ('chickpea'),
                                   ('chilli'),
                                   ('chipotle'),
                                   ('chips'),
                                   ('chive'),
                                   ('chocolate'),
                                   ('chopped'),
                                   ('chopping board'),
                                   ('chunky white fish fillet'),
                                   ('chutney'),
                                   ('ciabatta'),
                                   ('ciabatta loaf'),
                                   ('ciabatta roll'),
                                   ('cider'),
                                   ('cinnamon'),
                                   ('cinnamon stick'),
                                   ('clam'),
                                   ('clams in shell'),
                                   ('clear'),
                                   ('clear fruit-flavoured boiled sweet'),
                                   ('clementine'),
                                   ('clotted cream'),
                                   ('clove'),
                                   ('cm cake drum'),
                                   ('cm cooked shortcrust pastry tart case'),
                                   ('cm length of yellow ribbon'),
                                   ('cm-piece galangal'),
                                   ('co'),
                                   ('coarse white breadcrumbs'),
                                   ('coarsely grated fresh coconut'),
                                   ('cocktail stick'),
                                   ('cocoa powder'),
                                   ('coconut'),
                                   ('coconut cream'),
                                   ('coconut flakes'),
                                   ('coconut flavouring'),
                                   ('coconut flour'),
                                   ('coconut milk'),
                                   ('coconut oil'),
                                   ('coconut shaving'),
                                   ('coconut water'),
                                   ('cod'),
                                   ('coffee granule'),
                                   ('coffee sauce'),
                                   ('cointreau'),
                                   ('cola'),
                                   ('colander'),
                                   ('cold-pressed rapeseed'),
                                   ('coleslaw'),
                                   ('coley fillet'),
                                   ('coloured paper straw'),
                                   ('coloured sandwich flag'),
                                   ('coloured sprinkles'),
                                   ('colourful sprinkles'),
                                   ('conchiglioni'),
                                   ('cook''s blowtorch'),
                                   ('cooked'),
                                   ('cookie'),
                                   ('cooled instant coffee'),
                                   ('coriander'),
                                   ('cornflake'),
                                   ('cornflakes'),
                                   ('cornflour'),
                                   ('cottage cheese'),
                                   ('courgette'),
                                   ('courgetti'),
                                   ('couscou'),
                                   ('couscous'),
                                   ('cox'''),
                                   ('crabmeat'),
                                   ('cranberry'),
                                   ('cranberry juice'),
                                   ('cranberry sauce'),
                                   ('cream'),
                                   ('cream cheese'),
                                   ('creamed coconut'),
                                   ('creamed horseradish'),
                                   ('creamy parsnip mash'),
                                   ('cres'),
                                   ('crème fraîche'),
                                   ('crisps'),
                                   ('crostini'),
                                   ('crunchy summer veg'),
                                   ('crème de cacao'),
                                   ('crème de cassi'),
                                   ('crème fraîche'),
                                   ('crème fraîche and fresh herb'),
                                   ('cucumber'),
                                   ('cumin'),
                                   ('cumin seed'),
                                   ('cupcake case'),
                                   ('curd'),
                                   ('cured meat'),
                                   ('currant'),
                                   ('curry'),
                                   ('curry powder'),
                                   ('curry spice'),
                                   ('custard'),
                                   ('custard powder'),
                                   ('dairy'),
                                   ('dairy-free spread'),
                                   ('dairy-free sunflower spread'),
                                   ('danish blue is a good vegetarian one'),
                                   ('dark'),
                                   ('dashi'),
                                   ('date'),
                                   ('deep roasting tin'),
                                   ('demerara'),
                                   ('desiccated coconut'),
                                   ('dessert pastry'),
                                   ('dessert shortcrust pastry'),
                                   ('dill'),
                                   ('disaronno'),
                                   ('ditaloni rigati'),
                                   ('dolly mixture sweet'),
                                   ('dragon fruit'),
                                   ('drained mixed olive'),
                                   ('dressed green'),
                                   ('dried'),
                                   ('drinking straw'),
                                   ('duck'),
                                   ('dulce de leche'),
                                   ('each dried currant'),
                                   ('each red'),
                                   ('each white'),
                                   ('edamame bean'),
                                   ('edible flower'),
                                   ('edible flower petal'),
                                   ('edible glitter'),
                                   ('edible glue'),
                                   ('edible gold glitter'),
                                   ('edible gold lustre'),
                                   ('edible gold powder'),
                                   ('edible gold spray'),
                                   ('edible lustre spray in pink'),
                                   ('edible pearls and silver sprinkles'),
                                   ('egg'),
                                   ('eggs white'),
                                   ('elderflower cordial'),
                                   ('english breakfast tea bag'),
                                   ('eomuk'),
                                   ('espresso'),
                                   ('espresso powder'),
                                   ('extra blueberry'),
                                   ('extra firm tofu'),
                                   ('extra-firm tofu'),
                                   ('fajita seasoning'),
                                   ('fajita spice mix'),
                                   ('falafel'),
                                   ('fast-action'),
                                   ('fat'),
                                   ('fennel'),
                                   ('fennel seed'),
                                   ('fenugreek'),
                                   ('fenugreek seed'),
                                   ('feta'),
                                   ('feuille de brick'),
                                   ('feuilles de brick pastry'),
                                   ('field'),
                                   ('fig'),
                                   ('filo pastry'),
                                   ('filo pastry measuring 30 x 25cm'),
                                   ('filo pastry sheet'),
                                   ('fine dry breadcrumbs'),
                                   ('fine fresh white breadcrumbs'),
                                   ('fine semolina'),
                                   ('firm silken tofu'),
                                   ('firm tofu'),
                                   ('firm white fish fillet'),
                                   ('fish'),
                                   ('fish finger'),
                                   ('fish pie mix'),
                                   ('fish sauce'),
                                   ('fish stock'),
                                   ('five spice'),
                                   ('fl oz crème fraîche'),
                                   ('flageolet bean'),
                                   ('flaked'),
                                   ('flaked almonds and sprinkles'),
                                   ('flame raisin'),
                                   ('flatbread'),
                                   ('flavourless oil'),
                                   ('flaxseed'),
                                   ('flour'),
                                   ('floury roll'),
                                   ('floury soft white bap'),
                                   ('fontina'),
                                   ('forestière'),
                                   ('four-finger kitkat bar'),
                                   ('four-seed mix'),
                                   ('frankfurter'),
                                   ('free-range'),
                                   ('freekeh'),
                                   ('freeze-dried raspberry'),
                                   ('freeze-dried raspberry piece'),
                                   ('freeze-dried strawberry'),
                                   ('french dressing'),
                                   ('french fry'),
                                   ('french stick'),
                                   ('fresh'),
                                   ('from a small sliced brioche loaf'),
                                   ('fromage frai'),
                                   ('frozen'),
                                   ('fruit'),
                                   ('fruit and nut'),
                                   ('fruits of the forest'),
                                   ('full fat'),
                                   ('g/11-14oz piece of lean rump'),
                                   ('galliano'),
                                   ('garaetteok'),
                                   ('garam marsala'),
                                   ('garam masala'),
                                   ('garlic'),
                                   ('garlic powder'),
                                   ('gelatine'),
                                   ('ghee'),
                                   ('giant cookie'),
                                   ('giant couscou'),
                                   ('gin'),
                                   ('ginger'),
                                   ('gingerbread spice'),
                                   ('gingernut'),
                                   ('glucose syrup'),
                                   ('gluten'),
                                   ('gluten-free and vegan sprinkles'),
                                   ('gluten-free jumbo oats'),
                                   ('gluten-free oats'),
                                   ('gnocchi'),
                                   ('goat''s cheese'),
                                   ('gochujang'),
                                   ('goji berry'),
                                   ('gold'),
                                   ('gold edible glitter'),
                                   ('golden marzipan'),
                                   ('golden syrup'),
                                   ('good-quality'),
                                   ('goose fat'),
                                   ('gooseberry'),
                                   ('granary'),
                                   ('grand marnier'),
                                   ('granny smith'),
                                   ('granola'),
                                   ('grape'),
                                   ('grapefruit'),
                                   ('grated'),
                                   ('gravy'),
                                   ('green'),
                                   ('green and black olive with herb'),
                                   ('green bean'),
                                   ('green candy melt'),
                                   ('green olive'),
                                   ('green ready-to-roll icing'),
                                   ('green salad'),
                                   ('green spanish olive'),
                                   ('green tea'),
                                   ('green vegetable'),
                                   ('greens'),
                                   ('grenadine'),
                                   ('grenadine syrup'),
                                   ('grey mullet fillet'),
                                   ('ground coriander'),
                                   ('gruyère'),
                                   ('guacamole'),
                                   ('guava juice'),
                                   ('guinnes'),
                                   ('gurnard fillet'),
                                   ('haddock'),
                                   ('halibut'),
                                   ('halloumi'),
                                   ('ham'),
                                   ('hard nougat'),
                                   ('haricot bean'),
                                   ('harissa'),
                                   ('hazelnut'),
                                   ('hemp seed'),
                                   ('herb'),
                                   ('herb salad'),
                                   ('herbes de provence'),
                                   ('high-fibre puffed wheat'),
                                   ('hispi'),
                                   ('hoisin sauce'),
                                   ('hole doughnut tin'),
                                   ('honey'),
                                   ('honeycomb'),
                                   ('honeycomb piece'),
                                   ('horseradish'),
                                   ('horseradish mash'),
                                   ('horseradish sauce'),
                                   ('hot'),
                                   ('hot sauce'),
                                   ('houmou'),
                                   ('hummu'),
                                   ('hundreds and thousand'),
                                   ('ice'),
                                   ('ice cream'),
                                   ('icing eye'),
                                   ('icing rose'),
                                   ('icing sugar'),
                                   ('instant coffee'),
                                   ('instant coffee granule'),
                                   ('instant coffee powder'),
                                   ('instant espresso powder'),
                                   ('italian dried herb'),
                                   ('jackfruit'),
                                   ('jalapeño'),
                                   ('jam'),
                                   ('jerk'),
                                   ('jerk seasoning'),
                                   ('jersey royal'),
                                   ('jumbo oats'),
                                   ('jumbo porridge oat'),
                                   ('jumbo porridge oats'),
                                   ('juniper berry'),
                                   ('kaffir lime leaf'),
                                   ('kahlúa'),
                                   ('kalamata black olive'),
                                   ('kalamata olive'),
                                   ('kale'),
                                   ('kalonji seed'),
                                   ('kecap mani'),
                                   ('ketchup'),
                                   ('kettle'),
                                   ('kidney bean'),
                                   ('kitchen scissors'),
                                   ('kiwi'),
                                   ('korma paste'),
                                   ('lamb'),
                                   ('lard'),
                                   ('lasagne'),
                                   ('lasagne sheet'),
                                   ('lavender'),
                                   ('lavender flower'),
                                   ('leaf & herb salad'),
                                   ('leaf salad'),
                                   ('leafy salad'),
                                   ('leek'),
                                   ('leftover paella'),
                                   ('leftover pigs in blanket'),
                                   ('leftover roast'),
                                   ('lego fireman'),
                                   ('lemon'),
                                   ('lemon curd'),
                                   ('lemon sherbet'),
                                   ('lemon thyme'),
                                   ('lemonade'),
                                   ('lemongras'),
                                   ('lemongrass'),
                                   ('length rhubarb'),
                                   ('lentil'),
                                   ('lettuce'),
                                   ('levain'),
                                   ('light'),
                                   ('light brown'),
                                   ('light light crème fraîche'),
                                   ('light rapeseed'),
                                   ('lime'),
                                   ('limoncello'),
                                   ('liqueur'),
                                   ('liquorice catherine wheel'),
                                   ('little gem lettuces cut into'),
                                   ('loaf ciabatta'),
                                   ('lobster'),
                                   ('lollipop stick'),
                                   ('long ciabatta loaf'),
                                   ('long colourful ribbon'),
                                   ('lovage'),
                                   ('low fat crème fraîche'),
                                   ('low-sodium vegetable'),
                                   ('luxury seafood cocktail'),
                                   ('maca powder'),
                                   ('macadamia nut'),
                                   ('mace'),
                                   ('mackerel'),
                                   ('madeira cake'),
                                   ('madeira loaf cake'),
                                   ('madras spice paste'),
                                   ('make your own'),
                                   ('malibu'),
                                   ('malteser'),
                                   ('manchego'),
                                   ('mange tout'),
                                   ('mangetout'),
                                   ('mango'),
                                   ('maple syrup'),
                                   ('marinated seitan piece'),
                                   ('maris piper'),
                                   ('maris piper potatoes peeled'),
                                   ('marjoram'),
                                   ('marker pen'),
                                   ('marmalade'),
                                   ('marmite'),
                                   ('marrow'),
                                   ('marrowbone'),
                                   ('marsala'),
                                   ('marshmallow'),
                                   ('marzipan'),
                                   ('mascarpone'),
                                   ('mascarpone lite'),
                                   ('mash'),
                                   ('matcha powder'),
                                   ('matcha tea powder'),
                                   ('mature'),
                                   ('mature gruyère'),
                                   ('mayonnaise'),
                                   ('measuring jug'),
                                   ('measuring scale'),
                                   ('measuring spoon'),
                                   ('medium'),
                                   ('medjool date'),
                                   ('melon'),
                                   ('membrillo'),
                                   ('membrillo paste'),
                                   ('meringue'),
                                   ('meringue kiss'),
                                   ('metal pudding basin'),
                                   ('mild'),
                                   ('milk'),
                                   ('milkshake'),
                                   ('milled seed'),
                                   ('milled seeds with flax and chia'),
                                   ('mimosa balls and crystallised violet'),
                                   ('mincemeat'),
                                   ('mint'),
                                   ('mint sauce'),
                                   ('mirin'),
                                   ('miso'),
                                   ('mixed'),
                                   ('mixed bean'),
                                   ('mixed bean salad'),
                                   ('mixed beet'),
                                   ('mixed berry'),
                                   ('mixed black and green olive'),
                                   ('mixed dried fruit'),
                                   ('mixed dried herb'),
                                   ('mixed fresh fruit'),
                                   ('mixed fruit'),
                                   ('mixed grain'),
                                   ('mixed grain pouch'),
                                   ('mixed green'),
                                   ('mixed green salad'),
                                   ('mixed green vegetable'),
                                   ('mixed herb'),
                                   ('mixed leaf salad'),
                                   ('mixed nut'),
                                   ('mixed olive'),
                                   ('mixed peel'),
                                   ('mixed peppers cut into small'),
                                   ('mixed pitted olive'),
                                   ('mixed salad'),
                                   ('mixed salad leaves and low-fat dressing'),
                                   ('mixed seed'),
                                   ('mixed skinless fish fillet'),
                                   ('mixed spice'),
                                   ('mixed vegetable'),
                                   ('mixing bowl'),
                                   ('mixing spoon'),
                                   ('monkfish'),
                                   ('moong dal'),
                                   ('more frozen berry'),
                                   ('morel'),
                                   ('moroccan spice mix'),
                                   ('mozzarella'),
                                   ('mug frozen mixed vegetable'),
                                   ('mugful mixed dried fruit'),
                                   ('multi-coloured edible polka dot'),
                                   ('multicoloured candle'),
                                   ('mushroom'),
                                   ('mussel'),
                                   ('mustard'),
                                   ('mustard seed'),
                                   ('natural'),
                                   ('nectarine'),
                                   ('neri goma'),
                                   ('nettle'),
                                   ('nettle leave'),
                                   ('nigella seed'),
                                   ('noodle'),
                                   ('novelty candle'),
                                   ('nut'),
                                   ('nutmeg'),
                                   ('nuts of your choice'),
                                   ('oat'),
                                   ('oat and raisin cookie'),
                                   ('oat flakes'),
                                   ('oatmeal'),
                                   ('oats'),
                                   ('oil'),
                                   ('oil spray'),
                                   ('oil-based margarine'),
                                   ('okra'),
                                   ('olive'),
                                   ('olive oil'),
                                   ('olives of your choice'),
                                   ('omega seed mix'),
                                   ('one other salad'),
                                   ('onion'),
                                   ('onion powder'),
                                   ('onion seed'),
                                   ('opener'),
                                   ('optional fillings of lemon curd'),
                                   ('or 1 large ciabatta'),
                                   ('or 2 logs of soft'),
                                   ('or 2 small boneles'),
                                   ('or pack ready-made hollandaise sauce'),
                                   ('orange'),
                                   ('orange blossom water'),
                                   ('orecchiette'),
                                   ('oregano'),
                                   ('oven chips'),
                                   ('oven fry'),
                                   ('oven-roasted vegetable'),
                                   ('ox cheek'),
                                   ('oyster'),
                                   ('packet frozen fruits of the forest'),
                                   ('paella'),
                                   ('pak choi'),
                                   ('palm'),
                                   ('pancake'),
                                   ('paneer'),
                                   ('paper bag'),
                                   ('paper case'),
                                   ('paprika'),
                                   ('parmesan'),
                                   ('parsley'),
                                   ('parsnip'),
                                   ('party straw'),
                                   ('passata'),
                                   ('passion fruit'),
                                   ('passoa'),
                                   ('pasta'),
                                   ('pea'),
                                   ('pea protein'),
                                   ('peach'),
                                   ('peanut'),
                                   ('peanut butter'),
                                   ('pear'),
                                   ('peas in their pod'),
                                   ('pecan'),
                                   ('pecorino'),
                                   ('peeled'),
                                   ('pepper'),
                                   ('peppermint extract'),
                                   ('peppers of any colour'),
                                   ('peppery green salad'),
                                   ('peppery salad'),
                                   ('perilla'),
                                   ('pernod'),
                                   ('persimmon'),
                                   ('pesto'),
                                   ('petit pois'),
                                   ('petits pois'),
                                   ('pheasant crown'),
                                   ('pheasants leg'),
                                   ('piccalilli'),
                                   ('picked white crabmeat'),
                                   ('pickle'),
                                   ('pickled jalapeño'),
                                   ('piemento stuffed green olive'),
                                   ('pimento-stuffed olive'),
                                   ('pimm'''),
                                   ('pinch'),
                                   ('pine nut'),
                                   ('pineapple'),
                                   ('pineapple chunks in unsweetened juice'),
                                   ('pineapple juice'),
                                   ('pink'),
                                   ('pink and white marshmallow'),
                                   ('pink candy melt'),
                                   ('pink ready-to-roll icing'),
                                   ('pink rhubarb'),
                                   ('pinto'),
                                   ('pinto bean'),
                                   ('piping bag'),
                                   ('piri-piri marinade'),
                                   ('piri-piri sauce'),
                                   ('piri-piri spice mix'),
                                   ('pistachio'),
                                   ('pitta'),
                                   ('plaice'),
                                   ('plain'),
                                   ('plain pizza base'),
                                   ('plantain'),
                                   ('plastic diggers and one dumper truck'),
                                   ('plum'),
                                   ('plum tomato'),
                                   ('poached'),
                                   ('podded'),
                                   ('polenta'),
                                   ('pollock fillet'),
                                   ('pomegranate'),
                                   ('pomegranate juice'),
                                   ('popcorn'),
                                   ('popcorn kernel'),
                                   ('poppy seed'),
                                   ('pork'),
                                   ('porridge oat'),
                                   ('porridge oats'),
                                   ('port'),
                                   ('potato'),
                                   ('potato starch'),
                                   ('powdered malt drink'),
                                   ('prawn'),
                                   ('pre-cooked grain pouch'),
                                   ('preserved vine'),
                                   ('pretzel piece'),
                                   ('protein powder of your choice'),
                                   ('prune'),
                                   ('psyllium husk'),
                                   ('puff pastry'),
                                   ('puff pastry sheet'),
                                   ('puffed wheat'),
                                   ('pul biber'),
                                   ('pumpkin seed'),
                                   ('purple'),
                                   ('puy'),
                                   ('quantity barney''s roasted rhubarb'),
                                   ('quick'),
                                   ('quinoa'),
                                   ('rabbit'),
                                   ('radish'),
                                   ('rainbow sprinkles'),
                                   ('raisin'),
                                   ('raita'),
                                   ('raman'),
                                   ('rapeseed'),
                                   ('ras el hanout'),
                                   ('ras-el-hanout'),
                                   ('raspberry'),
                                   ('raspberry jelly'),
                                   ('raw'),
                                   ('ready salted crisps'),
                                   ('ready-rolled light puff pastry'),
                                   ('ready-rolled puff pastry'),
                                   ('ready-rolled puff pastry sheet'),
                                   ('ready-rolled sheet puff pastry'),
                                   ('ready-rolled shortcrust pastry'),
                                   ('ready-to-roll fondant icing'),
                                   ('ready-to-roll icing'),
                                   ('ready-to-roll lilac'),
                                   ('ready-to-roll pink icing'),
                                   ('ready-to-roll white icing'),
                                   ('red'),
                                   ('red berry'),
                                   ('red sugarpaste'),
                                   ('red wine'),
                                   ('red writing icing tube'),
                                   ('redcurrant jelly'),
                                   ('redcurrant sauce'),
                                   ('refried bean'),
                                   ('reposado tequila'),
                                   ('rhubarb'),
                                   ('rhubarb syrup'),
                                   ('rice'),
                                   ('ricotta'),
                                   ('ripe'),
                                   ('risotto'),
                                   ('rocket'),
                                   ('rolled oat'),
                                   ('rolled oats'),
                                   ('rolled porridge oats'),
                                   ('roquefort'),
                                   ('rose harrisa'),
                                   ('rose petal'),
                                   ('rosemary'),
                                   ('rosewater'),
                                   ('rough puff pastry'),
                                   ('round french country loaf'),
                                   ('round piping nozzle'),
                                   ('rounded tbsp apricot conserve'),
                                   ('rounded tbsp half-fat crème fraîche'),
                                   ('royal icing'),
                                   ('rum'),
                                   ('saffron'),
                                   ('sage'),
                                   ('saké'),
                                   ('salad'),
                                   ('salad cres'),
                                   ('salad leaves and slaw'),
                                   ('salmon'),
                                   ('salsa'),
                                   ('salsa dip'),
                                   ('salsa verde'),
                                   ('salt'),
                                   ('salted caramel'),
                                   ('sandwich flag'),
                                   ('sardine'),
                                   ('sauce'),
                                   ('saucepan'),
                                   ('sausage'),
                                   ('sausagemeat'),
                                   ('sausages of your choice'),
                                   ('sauterne'),
                                   ('savoy'),
                                   ('scallop'),
                                   ('scoops coffee'),
                                   ('sea bass'),
                                   ('seabass fillet'),
                                   ('seafood mix'),
                                   ('seafood selection'),
                                   ('seasonal greens and grain'),
                                   ('seasonal vegetable'),
                                   ('seasoning'),
                                   ('seeded burger bun'),
                                   ('seeded wrap'),
                                   ('selection of cake sprinkles'),
                                   ('semi-skimmed'),
                                   ('semolina'),
                                   ('sesame oil'),
                                   ('sesame seed'),
                                   ('shallot'),
                                   ('sharp knife'),
                                   ('sharp serrated knife'),
                                   ('shelled hemp seed'),
                                   ('sherry'),
                                   ('shop-bought'),
                                   ('shop-bought filo sheet'),
                                   ('shortbread'),
                                   ('shortcrust'),
                                   ('shortcrust pastry'),
                                   ('shortcrust pastry sheet'),
                                   ('sichuan'),
                                   ('side salad'),
                                   ('silken tofu'),
                                   ('silver ball'),
                                   ('skinles'),
                                   ('small'),
                                   ('small-leaf salad'),
                                   ('smarty'),
                                   ('smoked'),
                                   ('smoked paprika'),
                                   ('soda'),
                                   ('soda water'),
                                   ('soft'),
                                   ('soft date'),
                                   ('soft dried date'),
                                   ('soft fruit'),
                                   ('soft herb'),
                                   ('soft pitted date'),
                                   ('soft toffee'),
                                   ('soft white roll'),
                                   ('some blueberry'),
                                   ('somerset pomona'),
                                   ('sourdough'),
                                   ('sourdough starter'),
                                   ('soured cream'),
                                   ('soy'),
                                   ('soy sauce'),
                                   ('soya'),
                                   ('soya bean'),
                                   ('spanish pimento stuffed green olive'),
                                   ('sparkler'),
                                   ('sparkling grape juice'),
                                   ('sparkling water'),
                                   ('sparkling wine'),
                                   ('spelt'),
                                   ('spice piri-piri sauce'),
                                   ('spice powder'),
                                   ('spinach'),
                                   ('spirulina'),
                                   ('sponge finger'),
                                   ('spray of oil'),
                                   ('spray oil'),
                                   ('spring green'),
                                   ('spring onion'),
                                   ('sprinkles'),
                                   ('sprout top'),
                                   ('squash'),
                                   ('squid'),
                                   ('squids with tentacle'),
                                   ('sriracha'),
                                   ('stale breadcrumbs'),
                                   ('star'),
                                   ('star anise'),
                                   ('starfruit'),
                                   ('steamed bok choi'),
                                   ('steamed greens'),
                                   ('stewpack frozen vegetable'),
                                   ('sticky tape'),
                                   ('stinging'),
                                   ('stir-fry vegetable'),
                                   ('stock cube'),
                                   ('stoned date'),
                                   ('stoned prune'),
                                   ('strawberry'),
                                   ('strawberry conserve'),
                                   ('strong black coffee'),
                                   ('strong coffee'),
                                   ('strong espresso'),
                                   ('strong white'),
                                   ('sugar'),
                                   ('sultana'),
                                   ('sumac'),
                                   ('sunblush'),
                                   ('sundried'),
                                   ('sunflower'),
                                   ('sunflower seed'),
                                   ('sustainable white fish'),
                                   ('sustainable white fish fillet'),
                                   ('swede'),
                                   ('sweet pimenton'),
                                   ('sweet potato'),
                                   ('sweet shortcrust pastry'),
                                   ('sweetcorn'),
                                   ('sweets and sprinkles'),
                                   ('swiss chard'),
                                   ('syrup'),
                                   ('tablespoon'),
                                   ('taco'),
                                   ('taco shell'),
                                   ('tagine paste'),
                                   ('tagine spice paste'),
                                   ('tahini'),
                                   ('tamarind'),
                                   ('tamarind paste'),
                                   ('tarragon'),
                                   ('tartar sauce'),
                                   ('tartlet tin'),
                                   ('tea bag'),
                                   ('tea towel'),
                                   ('teabag'),
                                   ('teaspoon'),
                                   ('tequila'),
                                   ('thick'),
                                   ('thick caramel'),
                                   ('thick custard'),
                                   ('thick fillets white fish'),
                                   ('thick slices sourdough'),
                                   ('thick white fish fillet'),
                                   ('thin slices of brioche loaf'),
                                   ('thin slices rye sourdough'),
                                   ('thin-stemmed rhubarb'),
                                   ('thyme'),
                                   ('tiger prawns in their shell'),
                                   ('tikka masala paste'),
                                   ('tikka spice powder'),
                                   ('tilapia fillet'),
                                   ('timer'),
                                   ('toast and a balsamic-dressed salad'),
                                   ('toblerone'),
                                   ('toffee sauce'),
                                   ('tofu'),
                                   ('tomato'),
                                   ('tomato puree'),
                                   ('tomatoes cut into small'),
                                   ('tomatoes halved and sliced'),
                                   ('tomatoes on-the-vine'),
                                   ('tomatoes with herb'),
                                   ('tonic water'),
                                   ('tonic water and soda water'),
                                   ('toothpick'),
                                   ('toppings of your choice'),
                                   ('tortellini'),
                                   ('tortilla'),
                                   ('traditional oats'),
                                   ('treacle'),
                                   ('triple sec'),
                                   ('tropical fruit juice'),
                                   ('tropical fruit mix'),
                                   ('trout'),
                                   ('truffle oil'),
                                   ('tub coleslaw'),
                                   ('tub crème fraîche'),
                                   ('tub fresh custard'),
                                   ('tub fresh salsa'),
                                   ('tub fromage frai'),
                                   ('tub guacamole'),
                                   ('tub half-fat crème fraîche'),
                                   ('tub hummu'),
                                   ('tub low-fat crème fraîche'),
                                   ('tub low-fat fromage frai'),
                                   ('tub mascarpone'),
                                   ('tube smarty'),
                                   ('tubes of 6 ready-to-roll croissant'),
                                   ('tuna'),
                                   ('turkey'),
                                   ('turmeric'),
                                   ('turnip'),
                                   ('tzatziki'),
                                   ('unflavoured tempeh'),
                                   ('unroasted'),
                                   ('unsalted'),
                                   ('urad dal'),
                                   ('used ground coffee'),
                                   ('vanilla'),
                                   ('veg'),
                                   ('vegan bouillon powder'),
                                   ('vegan cookies of your choice'),
                                   ('vegan fermented kimchi'),
                                   ('vegan margarine'),
                                   ('vegan puff pastry block'),
                                   ('vegan spread'),
                                   ('vegan vegetable spread'),
                                   ('vegetable'),
                                   ('vegetable gravy granule'),
                                   ('vegetable oil'),
                                   ('vegetable stock'),
                                   ('vegetarian kefalotyri/ pecorino'),
                                   ('vegetarian mince'),
                                   ('vegetarian suet'),
                                   ('venison'),
                                   ('vermouth'),
                                   ('very strong coffee powder'),
                                   ('vinaigrette'),
                                   ('vine'),
                                   ('vinegar'),
                                   ('vodka'),
                                   ('wakame seaweed'),
                                   ('walnut'),
                                   ('wasabi'),
                                   ('water'),
                                   ('watercres'),
                                   ('watercress'),
                                   ('watermelon'),
                                   ('wheat'),
                                   ('wheat gluten'),
                                   ('whisky'),
                                   ('white'),
                                   ('white bean'),
                                   ('white breadcrumbs'),
                                   ('white country loaf'),
                                   ('white fish'),
                                   ('white fish fillet'),
                                   ('white fish fillets about 140g/5oz each'),
                                   ('white fondant icing'),
                                   ('white grape juice'),
                                   ('white icing'),
                                   ('white marzipan'),
                                   ('white ready-to-roll icing'),
                                   ('white ready-to-roll icing ''regal ice'),
                                   ('white skinless fish fillet'),
                                   ('white sugarpaste'),
                                   ('white wine'),
                                   ('whole'),
                                   ('wholemeal'),
                                   ('wholemeal breadcrumbs'),
                                   ('wholemeal bulghar wheat'),
                                   ('wholemeal bun'),
                                   ('wholemeal burger bun'),
                                   ('wholemeal couscou'),
                                   ('wholemeal giant couscou'),
                                   ('wholemeal toast'),
                                   ('wholemeal vegan breadcrumbs'),
                                   ('wholewheat giant couscou'),
                                   ('wholewheat lasagne sheet'),
                                   ('wine'),
                                   ('wooden spoon'),
                                   ('worcestershire sauce'),
                                   ('wrap'),
                                   ('writing icing'),
                                   ('xanthan gum'),
                                   ('xylitol'),
                                   ('yeast'),
                                   ('yellow'),
                                   ('yellow marzipan'),
                                   ('yellow sugarpaste'),
                                   ('yogurt'),
                                   ('your favourite dressing'),
                                   ('yuzu'),
                                   ('za''atar')
    ON CONFLICT (name) DO NOTHING;